# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f8036c63d23a4c593d4d7046c3d95dfb79bedcde35dff3ddb0918ca72f90a8b8eff0658f0613083f76d4bd2db6edc2c0220fd3054971ab3e10faccbfbda4925

test:
  secret_key_base: 4634ce0cca1c9ce5bd4f1e7d2ca812210e91f12e92b080a61ef5a6f622fd80c68daff9eb5d4ca0f8c7f2b253b8d6d086e2dae4ec29f8236a2ee1b21ba9e9ea71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
